<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/10/25 11:29:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecsite',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
