<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/11/06 09:13:35
sfConfig::add(array(
  'app_sf_upload_dir' => 'C:\\xampp\\htdocs\\development\\sfprojects\\ecsite/web/uploads',
));
