<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/11/05 06:58:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecsite',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
