<?php

/**
 * BaseCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $product_id
 * @property User $User
 * @property Product $Product
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getUserId()     Returns the current record's "user_id" value
 * @method integer getProductId()  Returns the current record's "product_id" value
 * @method User    getUser()       Returns the current record's "User" value
 * @method Product getProduct()    Returns the current record's "Product" value
 * @method Cart    setId()         Sets the current record's "id" value
 * @method Cart    setUserId()     Sets the current record's "user_id" value
 * @method Cart    setProductId()  Sets the current record's "product_id" value
 * @method Cart    setUser()       Sets the current record's "User" value
 * @method Cart    setProduct()    Sets the current record's "Product" value
 * 
 * @package    ecsite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}