<?php

/**
 * BaseOrderDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $product_name
 * @property decimal $total_amount
 * @property string $customer_name
 * @property text $delivery_address
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method string      getProductName()      Returns the current record's "product_name" value
 * @method decimal     getTotalAmount()      Returns the current record's "total_amount" value
 * @method string      getCustomerName()     Returns the current record's "customer_name" value
 * @method text        getDeliveryAddress()  Returns the current record's "delivery_address" value
 * @method OrderDetail setId()               Sets the current record's "id" value
 * @method OrderDetail setProductName()      Sets the current record's "product_name" value
 * @method OrderDetail setTotalAmount()      Sets the current record's "total_amount" value
 * @method OrderDetail setCustomerName()     Sets the current record's "customer_name" value
 * @method OrderDetail setDeliveryAddress()  Sets the current record's "delivery_address" value
 * 
 * @package    ecsite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_detail');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('product_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('total_amount', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             ));
        $this->hasColumn('customer_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('delivery_address', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}