<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/10/22 11:07:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ecsite',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
